# fly.toml app configuration file generated for dimitrisdotdev on 2023-06-02T00:09:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dimitrisdotdev"
primary_region = "lhr"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[mounts]
source = "dimitrisdotdev_data"
destination = "/data"
